import = [
    "~/.config/alacritty/themes/themes/lemongrass.toml"
]

[shell]
program = "/bin/zsh"

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 1
blur = true
decorations_theme_variant = "Dark"

[font]
normal = { family = "Dina", style = "Regular" }
size = 10

[cursor]
style = { shape = "Beam", blinking = "On" }
